export const mockCustomers = [
  {
    id: 'C001',
    name: 'Sarah Johnson',
    email: 'sarah.j@techcorp.io',
    company: 'TechCorp',
    plan: 'Enterprise',
    status: 'active',
    totalTickets: 14,
    openTickets: 1,
    satisfaction: 95,
    joinedAt: '2024-02-15',
    lastActivity: '2026-06-04T08:14:00Z',
    tags: ['enterprise', 'high-value'],
  },
  {
    id: 'C002',
    name: 'Marcus Lee',
    email: 'm.lee@enterprise.com',
    company: 'Enterprise Ltd',
    plan: 'Pro',
    status: 'active',
    totalTickets: 8,
    openTickets: 1,
    satisfaction: 92,
    joinedAt: '2024-05-20',
    lastActivity: '2026-06-03T14:30:00Z',
    tags: ['pro', 'power-user'],
  },
  {
    id: 'C003',
    name: 'Emily Watson',
    email: 'emily.w@startup.io',
    company: 'Startup.io',
    plan: 'Starter',
    status: 'active',
    totalTickets: 3,
    openTickets: 1,
    satisfaction: 88,
    joinedAt: '2025-11-10',
    lastActivity: '2026-06-04T06:55:00Z',
    tags: ['starter'],
  },
  {
    id: 'C004',
    name: 'David Kim',
    email: 'd.kim@globalcorp.com',
    company: 'GlobalCorp',
    plan: 'Enterprise',
    status: 'active',
    totalTickets: 22,
    openTickets: 0,
    satisfaction: 97,
    joinedAt: '2023-09-01',
    lastActivity: '2026-06-03T11:00:00Z',
    tags: ['enterprise', 'vip'],
  },
  {
    id: 'C005',
    name: 'Rachel Chen',
    email: 'r.chen@devshop.dev',
    company: 'DevShop',
    plan: 'Pro',
    status: 'active',
    totalTickets: 6,
    openTickets: 1,
    satisfaction: 91,
    joinedAt: '2025-03-14',
    lastActivity: '2026-06-03T16:45:00Z',
    tags: ['pro', 'developer'],
  },
  {
    id: 'C006',
    name: 'James Martinez',
    email: 'j.martinez@retail.co',
    company: 'RetailCo',
    plan: 'Business',
    status: 'active',
    totalTickets: 11,
    openTickets: 1,
    satisfaction: 89,
    joinedAt: '2024-08-22',
    lastActivity: '2026-06-03T09:10:00Z',
    tags: ['business'],
  },
  {
    id: 'C007',
    name: 'Olivia Park',
    email: 'o.park@mediahouse.com',
    company: 'MediaHouse',
    plan: 'Enterprise',
    status: 'suspended',
    totalTickets: 9,
    openTickets: 1,
    satisfaction: 86,
    joinedAt: '2024-01-30',
    lastActivity: '2026-06-04T07:30:00Z',
    tags: ['enterprise', 'at-risk'],
  },
  {
    id: 'C008',
    name: 'Tom Williams',
    email: 't.williams@corp.net',
    company: 'Corp.net',
    plan: 'Business',
    status: 'active',
    totalTickets: 5,
    openTickets: 0,
    satisfaction: 98,
    joinedAt: '2025-06-01',
    lastActivity: '2026-06-02T09:00:00Z',
    tags: ['business'],
  },
]
