export const mockArticles = [
  {
    id: 'KB001',
    title: 'Getting Started with SupportAI',
    category: 'Onboarding',
    status: 'published',
    views: 4821,
    helpful: 432,
    notHelpful: 12,
    updatedAt: '2026-05-20',
    author: 'Alex Rivera',
    tags: ['getting-started', 'onboarding'],
  },
  {
    id: 'KB002',
    title: 'How to Set Up SSO with Okta',
    category: 'Security',
    status: 'published',
    views: 2140,
    helpful: 198,
    notHelpful: 8,
    updatedAt: '2026-04-15',
    author: 'Priya Nair',
    tags: ['sso', 'okta', 'security'],
  },
  {
    id: 'KB003',
    title: 'API Rate Limits and How to Handle Them',
    category: 'API',
    status: 'published',
    views: 3560,
    helpful: 312,
    notHelpful: 15,
    updatedAt: '2026-05-10',
    author: 'Sam Thompson',
    tags: ['api', 'rate-limit', 'developer'],
  },
  {
    id: 'KB004',
    title: 'Understanding Your Invoice',
    category: 'Billing',
    status: 'published',
    views: 1890,
    helpful: 156,
    notHelpful: 22,
    updatedAt: '2026-03-28',
    author: 'Alex Rivera',
    tags: ['billing', 'invoice'],
  },
  {
    id: 'KB005',
    title: 'Resetting Your Password',
    category: 'Account',
    status: 'published',
    views: 5410,
    helpful: 498,
    notHelpful: 6,
    updatedAt: '2026-05-30',
    author: 'Priya Nair',
    tags: ['password', 'account', 'security'],
  },
  {
    id: 'KB006',
    title: 'Exporting Data to CSV',
    category: 'Data',
    status: 'draft',
    views: 0,
    helpful: 0,
    notHelpful: 0,
    updatedAt: '2026-06-01',
    author: 'Jordan Lee',
    tags: ['export', 'csv', 'data'],
  },
  {
    id: 'KB007',
    title: 'Troubleshooting Mobile App Sync Issues',
    category: 'Technical',
    status: 'published',
    views: 1240,
    helpful: 98,
    notHelpful: 31,
    updatedAt: '2026-05-18',
    author: 'Sam Thompson',
    tags: ['mobile', 'sync', 'troubleshooting'],
  },
  {
    id: 'KB008',
    title: 'Upgrading Your Plan',
    category: 'Billing',
    status: 'published',
    views: 2780,
    helpful: 241,
    notHelpful: 9,
    updatedAt: '2026-04-02',
    author: 'Alex Rivera',
    tags: ['upgrade', 'billing', 'plans'],
  },
]

export const categories = ['All', 'Onboarding', 'Security', 'API', 'Billing', 'Account', 'Technical', 'Data']
