export const mockTickets = [
  {
    id: 'TKT-1001',
    subject: 'Unable to process payment — card declined error',
    description: 'I keep getting a "card declined" error when trying to checkout. My card works fine on other sites. I have tried 3 different browsers and cleared my cache.',
    status: 'open',
    priority: 'urgent',
    category: 'Billing',
    customer: { id: 'C001', name: 'Sarah Johnson', email: 'sarah.j@techcorp.io', avatar: null, company: 'TechCorp' },
    assignee: { id: 'A001', name: 'Alex Rivera', avatar: null },
    createdAt: '2026-06-04T08:14:00Z',
    updatedAt: '2026-06-04T09:02:00Z',
    tags: ['payment', 'checkout', 'urgent'],
    aiSuggestion: 'This is likely a payment gateway timeout. Recommend checking with the billing team and guiding the customer to try a different payment method or contact their bank.',
    aiConfidence: 0.91,
    messages: [
      { id: 'm1', role: 'customer', content: 'I keep getting a "card declined" error when trying to checkout. My card works fine on other sites.', createdAt: '2026-06-04T08:14:00Z' },
      { id: 'm2', role: 'agent', content: 'Hi Sarah, I\'m sorry to hear you\'re having trouble with your payment. Can you confirm which card type you\'re using (Visa, Mastercard, etc.)?', createdAt: '2026-06-04T08:22:00Z' },
      { id: 'm3', role: 'customer', content: 'It\'s a Visa debit card. I\'ve tried Chrome, Firefox, and Safari — same error every time.', createdAt: '2026-06-04T08:35:00Z' },
      { id: 'm4', role: 'ai', content: 'Based on similar cases, this often occurs when the card\'s 3D Secure verification fails. I suggest asking the customer to contact their bank to enable online transactions, or offer PayPal as an alternative.', createdAt: '2026-06-04T08:36:00Z' },
    ],
    channel: 'email',
    sla: { breachAt: '2026-06-04T16:14:00Z', breached: false },
  },
  {
    id: 'TKT-1002',
    subject: 'Feature request: bulk export to CSV',
    description: 'Our team needs the ability to export all customer data to CSV in bulk. Currently we have to export page by page which is very time consuming.',
    status: 'pending',
    priority: 'medium',
    category: 'Feature Request',
    customer: { id: 'C002', name: 'Marcus Lee', email: 'm.lee@enterprise.com', avatar: null, company: 'Enterprise Ltd' },
    assignee: { id: 'A002', name: 'Priya Nair', avatar: null },
    createdAt: '2026-06-03T14:30:00Z',
    updatedAt: '2026-06-04T07:15:00Z',
    tags: ['feature-request', 'export', 'data'],
    aiSuggestion: 'This is a well-documented feature request. Log it in the product backlog and provide the customer with an ETA.',
    aiConfidence: 0.85,
    messages: [
      { id: 'm1', role: 'customer', content: 'We need bulk CSV export. This is slowing our team down significantly.', createdAt: '2026-06-03T14:30:00Z' },
      { id: 'm2', role: 'agent', content: 'Thanks for the feedback, Marcus. I\'ve logged this as a feature request with our product team. We\'ll keep you updated.', createdAt: '2026-06-03T15:00:00Z' },
    ],
    channel: 'portal',
    sla: { breachAt: '2026-06-06T14:30:00Z', breached: false },
  },
  {
    id: 'TKT-1003',
    subject: 'Login not working after password reset',
    description: 'I reset my password but now I cannot log in. The system says my credentials are invalid even though I just set the new password.',
    status: 'open',
    priority: 'high',
    category: 'Account',
    customer: { id: 'C003', name: 'Emily Watson', email: 'emily.w@startup.io', avatar: null, company: 'Startup.io' },
    assignee: null,
    createdAt: '2026-06-04T06:55:00Z',
    updatedAt: '2026-06-04T06:55:00Z',
    tags: ['login', 'password', 'account'],
    aiSuggestion: 'Password reset token may have expired or there is a caching issue. Guide the customer to clear cookies and try again, or generate a new reset link.',
    aiConfidence: 0.94,
    messages: [
      { id: 'm1', role: 'customer', content: 'I reset my password but cannot log in. It says invalid credentials.', createdAt: '2026-06-04T06:55:00Z' },
    ],
    channel: 'chat',
    sla: { breachAt: '2026-06-04T14:55:00Z', breached: false },
  },
  {
    id: 'TKT-1004',
    subject: 'Invoice #4421 shows incorrect amount',
    description: 'The invoice I received shows $299 but we agreed on $199 during the sales call. Please correct this.',
    status: 'resolved',
    priority: 'high',
    category: 'Billing',
    customer: { id: 'C004', name: 'David Kim', email: 'd.kim@globalcorp.com', avatar: null, company: 'GlobalCorp' },
    assignee: { id: 'A001', name: 'Alex Rivera', avatar: null },
    createdAt: '2026-06-02T10:20:00Z',
    updatedAt: '2026-06-03T11:00:00Z',
    tags: ['billing', 'invoice', 'pricing'],
    aiSuggestion: null,
    aiConfidence: null,
    messages: [
      { id: 'm1', role: 'customer', content: 'My invoice shows $299 but it should be $199 as agreed.', createdAt: '2026-06-02T10:20:00Z' },
      { id: 'm2', role: 'agent', content: 'David, I\'ve reviewed your account and confirmed the promotional rate. I\'ve issued a corrected invoice for $199 and a credit note for the difference.', createdAt: '2026-06-03T10:45:00Z' },
      { id: 'm3', role: 'customer', content: 'Perfect, thank you for resolving this quickly!', createdAt: '2026-06-03T11:00:00Z' },
    ],
    channel: 'email',
    sla: { breachAt: '2026-06-04T10:20:00Z', breached: false },
  },
  {
    id: 'TKT-1005',
    subject: 'API rate limit exceeded — need upgrade',
    description: 'We are hitting the 1000 req/min rate limit on the Pro plan. We need to discuss upgrading to Enterprise.',
    status: 'open',
    priority: 'medium',
    category: 'API',
    customer: { id: 'C005', name: 'Rachel Chen', email: 'r.chen@devshop.dev', avatar: null, company: 'DevShop' },
    assignee: { id: 'A002', name: 'Priya Nair', avatar: null },
    createdAt: '2026-06-03T16:45:00Z',
    updatedAt: '2026-06-04T08:30:00Z',
    tags: ['api', 'rate-limit', 'upgrade'],
    aiSuggestion: 'Opportunity to upsell to Enterprise plan. Suggest scheduling a call with an account executive.',
    aiConfidence: 0.88,
    messages: [
      { id: 'm1', role: 'customer', content: 'We are hitting the rate limit daily. Need to upgrade to Enterprise.', createdAt: '2026-06-03T16:45:00Z' },
      { id: 'm2', role: 'agent', content: 'Hi Rachel, I\'d be happy to discuss our Enterprise plan. Let me connect you with our account team.', createdAt: '2026-06-04T08:30:00Z' },
    ],
    channel: 'portal',
    sla: { breachAt: '2026-06-05T16:45:00Z', breached: false },
  },
  {
    id: 'TKT-1006',
    subject: 'Data sync not working between mobile and web',
    description: 'Changes made on mobile app are not syncing to the web dashboard. This started happening 2 days ago.',
    status: 'open',
    priority: 'high',
    category: 'Bug',
    customer: { id: 'C006', name: 'James Martinez', email: 'j.martinez@retail.co', avatar: null, company: 'RetailCo' },
    assignee: { id: 'A003', name: 'Sam Thompson', avatar: null },
    createdAt: '2026-06-03T09:10:00Z',
    updatedAt: '2026-06-04T07:45:00Z',
    tags: ['sync', 'mobile', 'bug'],
    aiSuggestion: 'Check if this correlates with the recent backend deployment on June 2. Escalate to engineering with device info.',
    aiConfidence: 0.79,
    messages: [
      { id: 'm1', role: 'customer', content: 'Data sync broken — mobile changes not showing on web since 2 days ago.', createdAt: '2026-06-03T09:10:00Z' },
    ],
    channel: 'chat',
    sla: { breachAt: '2026-06-04T17:10:00Z', breached: false },
  },
  {
    id: 'TKT-1007',
    subject: 'Account closed by mistake — need to restore',
    description: 'An admin on our team accidentally closed the account. We have critical data in there. Please restore immediately.',
    status: 'open',
    priority: 'urgent',
    category: 'Account',
    customer: { id: 'C007', name: 'Olivia Park', email: 'o.park@mediahouse.com', avatar: null, company: 'MediaHouse' },
    assignee: null,
    createdAt: '2026-06-04T07:30:00Z',
    updatedAt: '2026-06-04T07:30:00Z',
    tags: ['account', 'urgent', 'data-recovery'],
    aiSuggestion: 'Critical account restoration request. Escalate to senior support immediately. Check retention policy before proceeding.',
    aiConfidence: 0.97,
    messages: [
      { id: 'm1', role: 'customer', content: 'Our account was closed by mistake. We need it restored ASAP — critical data is at risk!', createdAt: '2026-06-04T07:30:00Z' },
    ],
    channel: 'email',
    sla: { breachAt: '2026-06-04T15:30:00Z', breached: false },
  },
  {
    id: 'TKT-1008',
    subject: 'How to set up SSO with Okta?',
    description: 'We want to enable SSO using Okta for our organization. Can you provide configuration steps?',
    status: 'closed',
    priority: 'low',
    category: 'How-to',
    customer: { id: 'C008', name: 'Tom Williams', email: 't.williams@corp.net', avatar: null, company: 'Corp.net' },
    assignee: { id: 'A001', name: 'Alex Rivera', avatar: null },
    createdAt: '2026-06-01T11:00:00Z',
    updatedAt: '2026-06-02T09:00:00Z',
    tags: ['sso', 'okta', 'security'],
    aiSuggestion: null,
    aiConfidence: null,
    messages: [
      { id: 'm1', role: 'customer', content: 'How do we set up SSO with Okta?', createdAt: '2026-06-01T11:00:00Z' },
      { id: 'm2', role: 'agent', content: 'Here is our step-by-step Okta SSO guide: [link]. Let me know if you need help with any step!', createdAt: '2026-06-01T11:30:00Z' },
      { id: 'm3', role: 'customer', content: 'Perfect, got it working. Thanks!', createdAt: '2026-06-02T09:00:00Z' },
    ],
    channel: 'portal',
    sla: { breachAt: '2026-06-03T11:00:00Z', breached: false },
  },
]

export const ticketStats = {
  open: 5,
  pending: 1,
  resolved: 1,
  closed: 1,
  totalToday: 12,
  resolvedToday: 7,
  avgResponseTime: '4m 32s',
  satisfactionScore: 94,
  aiResolutionRate: 68,
}
